import React, { ReactNode } from 'react';
import type { Metadata } from 'next';

import '@theme/scss/globals.scss';

import { AppProviders } from '@/shared/config/providers';
import Layout from '@/shared/ui/components/Layout/Layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='ru'>
      <body data-css='root'>
        <AppProviders>
          <Layout>{children}</Layout>
        </AppProviders>
      </body>
    </html>
  );
}
