import React, { ReactNode } from 'react';
import type { Metadata } from 'next';

import '@/assets/styles/index.scss';

import { AppProviders } from '@/shared/config/providers';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: ReactNode
}) {
	return (
		<html lang='ru'>
		<body><AppProviders>{children}</AppProviders></body>
		</html>
	);
}
